version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: local-postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=default
    restart: always